from sigstore_tsp.tsp import TimeStampRequest, TimeStampResponse

class PyMessageImprint: ...

class TimeStampReq: ...

class TimeStampResp: ...

class ObjectIdentifier: ...

class SignedData: ...

class PyTSTInfo: ...

class Accuracy: ...

def create_timestamp_request(
    data: bytes,
) -> TimeStampRequest: ...


def parse_timestamp_response(
    data: bytes,
) -> TimeStampResponse: ...
