from rfc3161_client.tsp import TimeStampRequest, TimeStampResponse

class PyMessageImprint: ...

class TimeStampReq: ...

class TimeStampResp: ...

class SignedData: ...

class PyTSTInfo: ...

class Accuracy: ...

class SignerInfo: ...

def create_timestamp_request(
    data: bytes,
    nonce: bool,
    cert: bool,
) -> TimeStampRequest: ...


def parse_timestamp_response(
    data: bytes,
) -> TimeStampResponse: ...
